// Generated by OrchestKit Claude Plugin
// Created: 2026-08-01

import { beforeEach, describe, expect, test, vi } from "vitest";

import { prisma } from "#lib/prisma.ts";
import { useTestDb } from "#test/db.ts";
import { api } from "#test/helpers.ts";

const getGoogleAuthUrl = vi.fn();
const getGoogleProfile = vi.fn();
vi.mock("./google.ts", () => ({
	getGoogleAuthUrl: () => getGoogleAuthUrl(),
	getGoogleProfile: (code: string) => getGoogleProfile(code),
}));

describe("auth routes (Google OAuth)", () => {
	useTestDb();

	beforeEach(() => {
		getGoogleAuthUrl.mockReset();
		getGoogleProfile.mockReset();
	});

	test("GET /auth/google redirects to the Google-provided authorization URL", async () => {
		getGoogleAuthUrl.mockReturnValue("https://accounts.google.com/mock-auth");

		const res = await api().get("/api/auth/google").expect(302);
		expect(res.headers.location).toBe("https://accounts.google.com/mock-auth");
	});

	test("GET /auth/google/callback redirects with an error flag when Google reports an error", async () => {
		const res = await api()
			.get("/api/auth/google/callback")
			.query({ error: "access_denied" })
			.expect(302);

		expect(res.headers.location).toBe(
			"http://localhost:3000/oauth/callback?error=1",
		);
		expect(getGoogleProfile).not.toHaveBeenCalled();
	});

	test("GET /auth/google/callback without a code returns 400", async () => {
		const res = await api().get("/api/auth/google/callback").expect(400);
		expect(res.body.code).toBe("invalid_argument");
	});

	test("creates a new user on first Google login and establishes a session", async () => {
		getGoogleProfile.mockResolvedValue({
			googleId: "google-id-new",
			email: "newperson@example.com",
		});

		const res = await api()
			.get("/api/auth/google/callback")
			.query({ code: "auth-code" })
			.expect(302);

		expect(res.headers.location).toBe("http://localhost:3000/oauth/callback");
		expect(res.headers["set-cookie"]).toHaveLength(2);

		const user = await prisma.user.findUnique({
			where: { googleId: "google-id-new" },
		});
		expect(user?.email).toBe("newperson@example.com");
		expect(user?.username).toBe("newperson@example.com");
	});

	test("reuses the existing user when the googleId already matches", async () => {
		const existing = await prisma.user.create({
			data: {
				username: "returning@example.com",
				email: "returning@example.com",
				googleId: "google-id-existing",
				passwordHash: null,
			},
		});

		getGoogleProfile.mockResolvedValue({
			googleId: "google-id-existing",
			email: "returning@example.com",
		});

		await api()
			.get("/api/auth/google/callback")
			.query({ code: "auth-code" })
			.expect(302);

		expect(await prisma.user.count()).toBe(1);
		const unchanged = await prisma.user.findUnique({
			where: { id: existing.id },
		});
		expect(unchanged?.googleId).toBe("google-id-existing");
	});

	test("links a Google identity to an existing local account matched by email", async () => {
		const localUser = await prisma.user.create({
			data: {
				username: "local-user",
				email: "shared@example.com",
				passwordHash: "seed:seed",
			},
		});

		getGoogleProfile.mockResolvedValue({
			googleId: "google-id-linked",
			email: "shared@example.com",
		});

		await api()
			.get("/api/auth/google/callback")
			.query({ code: "auth-code" })
			.expect(302);

		expect(await prisma.user.count()).toBe(1);
		const linked = await prisma.user.findUnique({
			where: { id: localUser.id },
		});
		expect(linked?.googleId).toBe("google-id-linked");
	});
});
